#!/usr/bin/env python3
"""Build the reviewed pet catalogue from the local Instagram download.
Requires Pillow. New/changed captions are rejected until curation is reviewed.
Usage: python3 scripts/import-instagram.py [downloads-directory]
"""
from pathlib import Path
from collections import Counter
import hashlib
import json
import re
import sys
from PIL import Image, ImageOps

PROJECT = Path(__file__).resolve().parents[1]
DOWNLOADS = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else PROJECT.parent / 'instagram_tool/downloads'
curation = json.loads((PROJECT / 'docs/instagram/curation.json').read_text())
review = json.loads((PROJECT / 'docs/instagram/post-review.json').read_text())
files = {f.parent.name: f for f in DOWNLOADS.rglob('*.txt')}
# Validate the entire input before writing any generated assets.
assert set(files) == {r['shortcode'] for r in review}, 'Download changed: review new/missing posts first.'
for r in review:
    assert hashlib.sha256(files[r['shortcode']].read_bytes()).hexdigest() == r['captionSha256'], f"Caption changed: review {r['shortcode']} first."
duplicates = {pet_id for pet_id, count in Counter(r['id'] for r in curation.values()).items() if count > 1}
assert duplicates == {'resgate-limao'}, f'Unreviewed identity merge: {duplicates}'
output = PROJECT / 'public/images/resgatados'
output.mkdir(parents=True, exist_ok=True)
pets = {}
image_manifest = []
for code, record in sorted(curation.items(), key=lambda x: files[x[0]].name):
    caption_file = files[code]
    originals = list(caption_file.parent.glob('*.jpg'))
    assert len(originals) == 1, f'Expected individually reviewed image: {code}'
    original = originals[0]
    im = ImageOps.exif_transpose(Image.open(original)).convert('RGB')
    width, height = im.size
    box = None
    if record['photoMode'] == 'frame':
        # Inset of the actual photograph inside the shared 1350 x 1687 template.
        box = tuple(round(v * scale) for v, scale in zip((312, 312, 1078, 1206), (width/1350, height/1687, width/1350, height/1687)))
    elif record['photoMode'] == 'olivia':
        # Keep the real cat and bed; omit the campaign title above the photo.
        box = (0, round(height * 0.36), width, height)
    if box:
        im = im.crop(box)
    im.thumbnail((960, 1100), Image.Resampling.LANCZOS)
    image_name = f'{record["id"]}-{code}.webp'
    im.save(output / image_name, 'WEBP', quality=88, method=6)
    source = {'url':f'https://www.instagram.com/p/{code}/','date':caption_file.name[:10],'kind':'Publicação individual'}
    extras = [{'url':f'https://www.instagram.com/p/{s["shortcode"]}/?img_index={s["slide"]}','date':s['date'],'kind':s['kind']} for s in record.get('extraSources',[])]
    body = re.sub(r'^ADOTAD[OA][\W_]*', '', caption_file.read_text().strip(), flags=re.I).split('#')[0].strip()
    # Merge only the confirmed alias pair: Limão / Limãozinho. Same names with
    # different photos and sex (two Ártemis) retain separate curated IDs.
    previous = pets.get(record['id'])
    photos = ([{'src':f'/images/resgatados/{image_name}','sourceUrl':source['url']}] + (previous['photos'] if previous else []))
    sources = ([source] + extras + (previous['sources'] if previous else []))
    sources = list({s['url']:s for s in sources}.values())
    pets[record['id']] = {
        **{k:record.get(k) for k in ['id','name','species','sex','age','ageDate','size','status']},
        'aliases':record.get('aliases',[]),
        'birthDate':record.get('birthDate'),
        'image':photos[0]['src'], 'photos':photos,
        'personality':record.get('personality', 'Situação de adoção a confirmar com o projeto.' if record['status']=='uncertain' else 'Uma história de resgate que encontrou um novo lar.'),
        'story':record.get('story',body),
        'storyIsCaption':'story' not in record,
        'traits':record.get('traits',[]),
        'care':record.get('care'),
        'requirements':record.get('requirements'),
        'statusNote':record.get('statusNote'),
        'sources':sources,
        'lastPublishedAt':max(s['date'] for s in sources),
    }
    image_manifest.append({'petId':record['id'],'source':str(original.relative_to(DOWNLOADS)), 'sourceSha256':hashlib.sha256(original.read_bytes()).hexdigest(),'output':f'public/images/resgatados/{image_name}','crop':box,'dimensions':list(im.size)})
pets = sorted(pets.values(), key=lambda p:p['lastPublishedAt'], reverse=True)
assert len({p['id'] for p in pets}) == len(pets)
assert all(p['ageDate'] if p['age'] else not p['ageDate'] for p in pets)
assert all(not p['care'] or p['sources'] for p in pets)
header = "// Generated by scripts/import-instagram.py from manually reviewed records.\nimport type { Pet } from './pet-types'\n\nexport const pets: Pet[] = "
(PROJECT / 'src/data/rescue-catalog.ts').write_text(header+json.dumps(pets,ensure_ascii=False,indent=2)+'\n')
(PROJECT / 'docs/instagram/image-manifest.json').write_text(json.dumps(image_manifest,ensure_ascii=False,indent=2)+'\n')
counts = Counter(p['status'] for p in pets)
lines = ['# Revisão dos posts do Instagram', '', 'Fonte: `umbra-studios/instagram_tool/downloads`. Revisão em 05/09/2026.', '', f'{len(review)} posts e {sum(len(list(f.parent.glob("*.jpg"))) for f in files.values())} imagens avaliados. {len(pets)} perfis individuais: {counts["seeking"]} em busca de lar nas fontes, {counts["uncertain"]} com situação conflitante e {counts["adopted"]} marcados como adotados.', '', 'Idades e cuidados são históricos, vinculados às datas das publicações. Nenhuma disponibilidade foi confirmada em tempo real. Legendas editadas não trazem a data da edição; por isso, anúncios de adoção que conflitam com cartinhas posteriores ficam como situação a confirmar.', '', 'Limão e Limãozinho foram reunidos; os dois Ártemis e as duas Jasmin foram distinguidos. Jasmin da ninhada Princesas faleceu e não está no catálogo. Tratamentos, colônias e animais sem associação segura entre nome e foto não foram convertidos em anúncios de adoção.', '', 'Os recortes removem a moldura gráfica sem gerar ou alterar a aparência dos animais. Originais permanecem nos downloads. Coordenadas, hashes e arquivos de saída estão em `image-manifest.json`.', '', '## Análise de cada publicação', '']
for r in review:
    code=r['shortcode']; c=curation.get(code)
    lines += [f'### {r["date"]} · {code}', '', f'[Abrir publicação](https://www.instagram.com/p/{code}/)', '', f'**Decisão:** {r["decision"]}']
    if c:
        pet=next(p for p in pets if p['id']==c['id'])
        lines += [f'**Perfil:** {c["name"]} (`{c["id"]}`) · situação: `{pet["status"]}`.', f'**Idade catalogada:** {c["age"] or "não informada"} (fonte: {c["ageDate"] or "não informada"}). **Sexo:** {c["sex"] or "não informado"}. **Porte:** {c["size"] or "não informado"}.']
        lines += c.get('reviewNotes',[])
        if c.get('extraSources'):lines.append('Também confrontado com imagens das cartinhas de Natal associadas no cadastro.')
    lines += ['', '<details>', '<summary>Legenda original preservada para conferência</summary>', '', files[code].read_text().strip(), '', '</details>', '']
(PROJECT / 'docs/instagram/REVIEW.md').write_text('\n'.join(lines))
print(f'Validated {len(review)} posts; built {len(pets)} pets and {len(image_manifest)} photos. Status counts: {dict(counts)}')
print(f'Photo total: {sum((output/Path(m["output"]).name).stat().st_size for m in image_manifest)/1024/1024:.1f} MiB')
